feat: 이미지 컴포넌트
HeeHeePresso/heehee-fe pull request #24
Opened 2024-04-09 08:48 UTC by sinamong0620

<img width="390" alt="스크린샷 2024-04-09 오후 5 44 45" src="https://github.com/HeeHeePresso/heehee-fe/assets/114804676/71d22b0f-c41a-4bb7-a8b1-f9a9bb5dda01">

스토리북에서 이미지 비율 설정 가능하게 했는데요. 이슈에 올려주신 과제에서 선택 과제 제외하고 필수인건 일단 했습니다. 근데 제가 일단 이렇게 하는건지 잘 모르겠어서 일단 커밋 올렸습니다. 
고쳤으면 하는 코드가 보이시면 말해주셨으면 좋겠습니다.

2024-04-14 17:53 UTC, NariP reviewed
포멧팅이 아직 안되어 있는걸로 보이네요.
세팅 해주시고 만약 잘 모르시겠으면 @say-young516 님께 물어보시면 될 것 같습니다ㅎㅎ

2024-04-19 13:53 UTC, NariP requested changes
고생 많으셨습니다! 👍

2024-04-19 13:53 UTC, NariP commented on packages/hds/src/components/Image/Img.tsx
> +    <div className={container}>
[질문]
div로 한 번 감싼 이유가 궁금합니다. 없어도 동작하지 않나요?

2024-04-19 13:53 UTC, NariP commented on packages/hds/src/components/Image/Img.tsx
> +  const [imgSrc,setImgSrc] = useState(src);
[필수]
스토리북에서 이미지 src 를 수정했을 때 반영이 되지 않고 있습니다.
line16 과 관련 있으니 수정해주세요.

리액트의 useState 의 initialState 는 처음 렌더링 시에만 사용합니다. 즉, props 의 src 가 변경이 되어도 imgSrc 는 알아서 변경이되지 않는다는 의미 입니다.

<img width="445" alt="image" src="https://github.com/HeeHeePresso/heehee-fe/assets/23569208/86028493-2aeb-46c6-ad56-a57972ae5fae">

2024-05-04 08:56 UTC, sinamong0620 commented on packages/hds/src/components/Image/Img.tsx
> +import noImage from "../../../../../src/Images/noImage.png";
저번에 제 코드 잠깐 봐주시면서 public 폴더에 Images 폴더를 위치시켰을때 번들링 과정에서 public 폴더는 쏙 빠지게 되어서 문제가 있을 거라고 하셔서 src폴더에 Images폴더를 위치시켰습니다.
번들링 과정에서 pulic 폴더가 제외되었을때 이미지 파일들이 자동으로 압축되지않아 로딩시간이 길어지는 문제가 있는걸로 알고 있는데저번에 이 문제 때문에 다른 폴더로 변경하는게 좋을 것 같다는 말씀을 해주신게 맞나요..?

2024-05-04 08:57 UTC, sinamong0620 commented on packages/hds/src/components/Image/Image.css.ts
> + export const ratios = {
앗 사실 제가 recipe를 쓰는게 너무 복잡해보여서 돌아서 다른 방식으로 간단하게 해보는 걸로 구현했습니다..
다시 개발 문서 정독하고 recipe로 수정하겠습니다!

2024-05-04 14:18 UTC, sinamong0620 commented on packages/hds/src/components/Image/Img.stories.tsx
> +const meta:Meta<typeof Img> = {
뭔소린지 모르고 뭐든 쓰자 해서 썼는데 이제보니 타입이 두 번 명시되어 있네요. 얼른 수정하겠습니다!..

2024-05-04 16:35 UTC, NariP commented on packages/hds/src/components/Image/Image.css.ts
> + export const ratios = {
제안이라 굳이 수정 안하셔도 됩니다~
이런 방법도 있다 라고 아시면 돼요ㅎㅎ

2024-05-05 17:10 UTC, sinamong0620 commented on packages/hds/src/components/Image/Img.tsx
> +    <div className={container}>
제가 처음에 어떤 방식으로 생각했냐면 div를 하나 더 감싸서 div에 width,heigth값을 주고 img의 width,height값을 100%로 주어서 컨테이너에 따라서 img의 크기가 비율에 맞게 변경될 수 있도록 조절하려고 했습니다... 그래서 이렇게 하면 이미지가 깨지지 않을거라고 생각해서 div로 한번 더 감싼 이유였습니다.

2024-05-05 17:11 UTC, sinamong0620 commented on packages/hds/src/components/Image/Img.tsx
> +  // const [w,h] = ratio.split("/").map(Number);
제거 완료 했습니다.

2024-05-05 17:12 UTC, sinamong0620 commented on packages/hds/src/components/Image/Image.css.ts
> +   backgroundColor : "black",
아래에서 코멘트 해주신 것처럼 object-fit 속성을 사용할 생각을 못했어서 img를 100%로 반영했습니다. 바로 object-fit으로 수정할 수 있도록 하겠습니다.

2024-05-06 05:36 UTC, NariP commented on packages/hds/src/components/Image/Img.tsx
> +import noImage from "../../../../../src/Images/noImage.png";
**간단한 설명**
public 폴더는 프레임워크, 보일러플레이트마다 다르게 동작할 수는 있지만,
nextJs, cra, vite 의 경우만 이야기해보자면

public 에 넣은 파일들은 번들링 과정에 포함되지 않고
번들링된 결과물 예를 들어 dist 폴더에 그대로 복사되는 과정을 거칩니다.

1. public 폴더 이하
    - 번들에 포함되지 않음 > 이미지 최적화 X
    - 번들 외부 파일에서도 사용 가능(ex. index.html 에서 파비콘 설정을 위한 svg를 import 할 때)
    - 회사에 따라 다르겠지만? 정적 콘텐츠의 외부 스토리지 연결을 할 때 사용(개발 환경에서는 '/images/image.jpg' 라고 호출했지만 번들러 설정에 의해 외부 스토리지 주소가 붙어 ('<s3 스토리지 주소>/images/image.jpg') 이런식으로 호출됨
    - 이미지 로드에 실패할 수도 있음
2. src 이하(번들러에 지정된 엔트리 포인트 아래)
    - 번들에 포함됨 > 이미지 최적화 및 압축 작업이 실행됨(번들러에 설정했다면)
    - 번들 내부에서 자유롭게 경로로 import 가능

**질문한 의도**
- 패키지 내부에 위치시키지 않고 패키지 외부에 이미지를 위치시킨 이유가 궁금해서 물어봤습니다.

**제안**
- 이미지 로드 실패했을 때 보여줄 이미지는 또 로드 실패하면 안되니까 번들 에셋에 포함시키는게 좋을 것 같네요.
- 그리고 그 실패 이미지는 이미지 컴포넌트(즉, 패키지 내부)에서만 호출할 것으로 예상되니 packages/hds/systems/images 내부에 넣어주세요.

**질문에 대한 대답**
Q. public 폴더에 Images 폴더를 위치시켰을때 번들링 과정에서 public 폴더는 쏙 빠지게 되어서 문제가 있을 거라고 하셔서..?
- 그때 기억으로는 public 폴더의 이미지를 일반 번들에 포함된 이미지를 불러오듯이 import 를 해서 문제가 생겼던걸로 기억하네요.

Q. 번들링 과정에서 pulic 폴더가 제외되었을때 이미지 파일들이 자동으로 압축되지않아 로딩시간이 길어지는 문제가 있는걸로 알고 있는데저번에 이 문제 때문에 다른 폴더로 변경하는게 좋을 것 같다는 말씀을 해주신게 맞나요..?
- 그 때 설명한건 설명한거고, 다른 폴더로 변경하라고 했던건 import 경로 문제로 이미지가 보여지지 않고 있기 때문에 그랬을거에요.
- 아무튼 저희는 외부 스토리지도 사용안하고 그러니까 편하게 아래처럼 생각하시면 될 것 같네요.
    - packages/hds 내부에서만 사용한다 -> packages/hds/systems/images 아래에 위치
    - hds 에서는 사용안하는데 외부에서는 사용한다 -> 루트의 src 이하에 위치(폴더명은 assets 뭐 이런식으로 해주세요, 이미지 말고 다른 것도 넣을 수도 있으니)
    - index.html 에서 사용해야한다 -> public 아래에 위치

2024-05-07 07:08 UTC, sinamong0620 commented on packages/hds/src/components/Image/Img.tsx
> +      <Image ref={ref} src={imgSrc} alt="img" width={100} height={100} className={`${ratios[ratio]} ${imageStyle}`} onError={changeSrcFunc}/>
나리님 혹시 alt,width,height 이 세가지를 스토리북에서 control로 값을 받아서 이 값을 Img 컴포넌트에 props로 전달하는 걸로 이해해도 될까요?

2024-05-07 14:38 UTC, sinamong0620 commented on packages/hds/src/components/Image/Img.tsx
> +interface Image {
수정했습니다.

2024-05-07 14:39 UTC, sinamong0620 commented on packages/hds/src/components/Image/Img.tsx
> +  const [imgSrc,setImgSrc] = useState(src);
수정해서 commit 올렸습니다. 업데이트한 코드 내용 보시고 피드백 해주시면 감사드리겠습니다.

2024-05-07 14:52 UTC, NariP commented on packages/hds/src/components/Image/Image.css.ts
> +  backgroundColor: 'gray',
globalStyle?거기에 정의되어있는 컬러 사용해주세요~

2024-05-07 15:45 UTC, sinamong0620 commented on packages/hds/src/components/Image/Img.tsx
> +      <Image ref={ref} src={imgSrc} alt="img" width={100} height={100} className={`${ratios[ratio]} ${imageStyle}`} onError={changeSrcFunc}/>
stories 파일에서 width, height의 default 값을 0으로 설정했습니다. 사용자에게 인가하면 된다고 말씀해주셔서 일단 값을 설정하긴 했는데 맞는 방식인지는 잘 모르겠습니다. 
alt는 사용하는 쪽에서 변경하는 것을 확인했는데 width,height는 변경을 해도 변경이 되지 않더라구요. object-fit 에서 비율을 사용하는 것이라서 width,height값을 굳이 사용할 필요가 없다는 것으로 이해하긴 했습니다.. 

1. 그렇다면 width,height값이 아예 필요없는 것은 아닐까? 사진의 px만큼 알아서 설정되는거 같은데.. 
2. 만일 필요하다면 width,height의 기본 값을 설정하는걸 args에 width:0 height:0 으로 넘겨주는 방식이 맞는것인지..! 
라는 지점이 궁금했습니다.

[9a26d6e](https://github.com/HeeHeePresso/heehee-fe/pull/24/commits/9a26d6ef79368108b6fb9f83f235928d3d948cb0)
[dbb13c4](https://github.com/HeeHeePresso/heehee-fe/pull/24/commits/dbb13c46badf7aeccb13758b5aad59e798f2eaa4)

2024-05-12 08:36 UTC, merged